collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 1
color:
  saturation: 0.8735244
  brandStrength: 0.772344
  lightness: 0.04763776
  brandColors:
    - '#FFFFFF'
    - '#D8BEA3'
    - '#1F0C04'
    - '#776478'
    - '#9A271F'
  rhythmicContrast: 0.8347386
layout_spectrum: 0.6551433
name: Fosterandflourish
