collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.8996627
color:
  saturation: 0.9662732
  brandStrength: 0.1871838
  lightness: 0.9620574
  brandColors:
    - '#DF2830'
    - '#FFFFFF'
    - '#420E0D'
    - '#F2A339'
    - '#C5D965'
  rhythmicContrast: 0.4890388
layout_spectrum: 0.1526138
name: Fosterandflourish
