collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.5910624
  brandStrength: 0.8077571
  lightness: 0.5514334
  brandColors:
    - '#DF2830'
    - '#FFFFFF'
    - '#420E0D'
    - '#F2A339'
    - '#C5D965'
  rhythmicContrast: 0.01096121
typography_spectrum: 0.8996627
layout_spectrum: 0.1526138
name: Fosterandflourish
