layout_spectrum: 0.1030172
typography_spectrum: 0.7624866
color:
  saturation: 0.4505798
  lightness: 0.04763776
  brandStrength: 0.1622523
  rhythmicContrast: 0.624813
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
name: Fosterandflourish
