name: Fosterandflourish
favicon: null
layout_spectrum: 0.6551433
typography_spectrum: 0.8996627
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#d5bfae'
    - '#210c04'
    - '#7b6779'
    - '#04544d'
  brandStrength: 0.625
  lightness: 0.1875
  saturation: 0.0625
  rhythmicContrast: 1
purpose: []
