name: Fosterandflourish
favicon: null
layout_spectrum: 0.37277
typography_spectrum: 0.63873
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#c2c2c2'
    - '#131313'
    - '#616161'
    - '#8a8a8a'
  brandStrength: 0.1622523
  lightness: 0.04763776
  saturation: 0.4505798
  rhythmicContrast: 0.75
purpose: []
