name: Fosterandflourish
favicon: null
layout_spectrum: 0.6551433
typography_spectrum: 0.8996627
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ebe2db'
    - '#d5a078'
    - '#0e0603'
    - '#a85c3a'
    - '#6b3712'
  brandStrength: 0.875
  lightness: 0.1875
  saturation: 0.0625
  rhythmicContrast: 0.75
purpose: []
